version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: snmp-simulator

# archives:
#   - formats: ["tar.gz"]
#     # this name template makes the OS and Arch compatible with the results of `uname`.
#     name_template: >-
#       {{ .ProjectName }}_
#       {{- title .Os }}_
#       {{- if eq .Arch "amd64" }}x86_64
#       {{- else if eq .Arch "386" }}i386
#       {{- else }}{{ .Arch }}{{ end }}
#       {{- if .Arm }}v{{ .Arm }}{{ end }}
#     # use zip for windows archives
#     format_overrides:
#       - goos: windows
#         format: zip

docker_manifests:
  - name_template: "ghcr.io/calimapp/snmp-simulator:{{ .Tag }}"
    image_templates:
      - "ghcr.io/calimapp/snmp-simulator:{{ .Tag }}-amd64"
      - "ghcr.io/calimapp/snmp-simulator:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/calimapp/snmp-simulator:latest"
    image_templates:
      - "ghcr.io/calimapp/snmp-simulator:{{ .Tag }}-amd64"
      - "ghcr.io/calimapp/snmp-simulator:{{ .Tag }}-arm64"

dockers:
  - image_templates:
      - "ghcr.io/calimapp/snmp-simulator:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
  - image_templates:
      - "ghcr.io/calimapp/snmp-simulator:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    goarch: arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"