{{- if $.Values.serviceAccount.create }}
{{ print "---" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.serviceAccount.name }}
  namespace: {{ include "namespace" $ }}
{{- end -}}