{{- range $i, $device := $.Values.devices }}
{{ print "---" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ $device.name }}-svc
  namespace: {{ include "namespace" $ }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/instance: {{ $.Chart.Name }}-{{ $device.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $device.polling.port }}
      targetPort: snmp-get
      protocol: UDP
      name: snmp-get
  selector:
    {{- include "common.labels" $ | nindent 4 }}
    app.kubernetes.io/instance: {{ $.Chart.Name }}-{{ $device.name }}
{{- end }}